# Dockerfile.flask

FROM python:3.7-alpine

RUN mkdir /app
WORKDIR /app
ENV PYTHONPATH /app

RUN apk update
RUN apk add --no-cache bash git py3-gunicorn
	
COPY requirements.txt /requirements.txt
RUN python -m pip install -r /requirements.txt

COPY ./.env /app/
COPY ./app /app
COPY ./static /static

# Expose the listening port
EXPOSE 5000

#ENTRYPOINT ["/usr/bin/gunicorn", "-b", "0.0.0.0:$PORT", "synctool:app"]
ENTRYPOINT ["gunicorn", "-b", "0.0.0.0:5000", "synctool:app"]