# Dockerfile.flask

FROM python:3.7-alpine

RUN apk update
RUN apk add --no-cache bash git py3-gunicorn py3-flask	\
	&& pip3 install flask flask-cors
	
COPY requirements.txt /requirements.txt
RUN pip3 install -r requirements.txt
	
COPY ./app /app
COPY ./static /static

ENV PYTHONPATH /app

# Expose the listening port
EXPOSE 5000

#ENTRYPOINT ["/usr/bin/gunicorn", "-b", "0.0.0.0:$PORT", "synctool:app"]
ENTRYPOINT ["/usr/bin/gunicorn", "-b", "0.0.0.0:5000", "synctool:app"]