# Dockerfile.nginx

FROM nginx:latest

EXPOSE 80

# Remove default config file
RUN rm /etc/nginx/conf.d/default.conf

# Copy our config file to replace the one we deleted
COPY nginx.conf /etc/nginx/conf.d/app.conf