# docker-compose.yml

version: '3'
services:
  ebaysync-flask:
    image: ebaysync-flask
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - "./app:/app"                            # Map the repo "app" directory to the container 
                                                #   so we don't have to rebuild when we make edits
  nginx:
    image: ebaysync-nginx
    build:                                      # Build the nginx container
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - "./static:/usr/share/nginx/html"        # Map the repo "static" directory to the Nginx webroot
                                                #   so we don't have to rebuild when we make edits to
                                                #   static files
    ports:
      - 5000:80                                 # Expose this container's port 80 on the local machine port 5000
    depends_on:
      - ebaysync-flask                          # Create a network with both images and